version: 2.1

executors:
  node:
    docker:
      - image: node:alpine

commands:
  install-node-deps:
    description: "Install Node dependencies"
    steps:
      - run: 
          name: "Install Node Deps"
          command: npm ci

jobs:
  types-check:
    executor: node
    steps:
      - checkout
      - install-node-deps
      - run:
          name: "Types Checking"
          command: npm run types:check
      
  format-check:
    executor: node
    steps:
      - checkout
      - install-node-deps
      - run:
          name: "Format Checking"
          command: npm run format:check

  lint-check:
    executor: node
    steps:
      - checkout
      - install-node-deps
      - run:
          name: "Lint Checking"
          command: npm run lint

  unit-tests:
    executor: node
    steps:
      - checkout
      - install-node-deps
      - run:
          name: "Execute units tests"
          command: npm run test

  build:
    docker:
      - image: node:alpine
    steps:
        - checkout
        - install-node-deps
        - run:
            name: "Build package"
            command: npm run build
# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  Global-checking:
    jobs:
      - types-check
      - format-check
      - lint-check
      - unit-tests
      - build:
          requires:
            - types-check
            - format-check
            - lint-check
            - unit-tests
