version: 2.1

executors:
  node:
    docker:
      - image: node:alpine

commands:
  install-node-deps:
    description: "Install Node dependencies"
    steps:
      - run: 
          name: "Install Node Deps"
          command: npm ci --cache .npm --prefer-offline --no-audit --silent
  restore-deps-cache:
    description: "Cache restoration of node dependencies"
    steps:
      - restore_cache:
          keys: 
            - deps-{{ .Branch }}-{{ checksum "package-lock.json" }}
  


jobs:
  deps-install:
    executor: node
    steps:
      - checkout
      - install-node-deps
      - save_cache:
          key: deps-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - .npm
  types-check:
    executor: node
    steps:
      - checkout
      - restore-deps-cache
      - install-node-deps
      - run:
          name: "Types Checking"
          command: npm run types:check
      
  format-check:
    executor: node
    steps:
      - checkout
      - restore-deps-cache
      - install-node-deps
      - run:
          name: "Format Checking"
          command: npm run format:check

  lint-check:
    executor: node
    steps:
      - checkout
      - restore-deps-cache
      - install-node-deps
      - run:
          name: "Lint Checking"
          command: npm run lint

  unit-tests:
    executor: node
    steps:
      - checkout
      - restore-deps-cache
      - install-node-deps
      - run:
          name: "Execute units tests"
          command: npm run test

  build:
    docker:
      - image: node:alpine
    steps:
        - checkout
        - restore-deps-cache
        - install-node-deps
        - run:
            name: "Build package"
            command: npm run build
# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  Global-checking:
    jobs:
      - deps-install
      - types-check:
          requires:
            - deps-install
      - format-check:
          requires:
            - deps-install
      - lint-check:
          requires:
            - deps-install
      - unit-tests:
          requires:
            - deps-install
      - build:
          requires:
            - types-check
            - format-check
            - lint-check
            - unit-tests
